print('divident / divisor = quotient')
print()
x = int(input("Digit an integer divident:"))
y = int(input("Now digit an integer divisor:"))
print()
print('The value of the operation using operador / is', (x/y), 'because this is a normal division.')
print('Depeding of the number we choose, we can have as result a INTEGER or a FLOAT number.')
print()
print('but if we use //, we will always get a INTEGER number, never ever FRACTIONAL (FLOAT). Never!')
print('The value of the operation using operador // is', (x//y),'.')
print()
print('In case we choose numbers that do not generate a precise division,')
print('the quocient produce some number left and we want to know how much left,')
print('in that case we will use %')
print()
print('A normal division of', x,'by', y,'is precisely', (x/y),',')
print('but a division of', x,' by', y,'not considering any eventual fration is', (x//y))
print('and eventual fration is', (x%y))