print('divident / divisor = quotient')
print()
x = int(input("Digit an integer divident:"))
y = int(input("Now digit an integer divisor:"))
print()
print('1. The value of the operation using operador / is', (x/y), 'because this is a normal division.')
print('Depeding of the number we choose, we can have as result a INTEGER or a FLOAT number.')
print()
b1 = input('')
print()
print('2. but if we use //, we will always get a INTEGER number, never ever FRACTIONAL (FLOAT). Never!')

print('The value of the operation using operador // is', (x//y),'.')
print('It occurs because the fractional part is not being taking in consideration')

print('if we had a fractinal in the item 1 (',((x/y)-(x//y)),')it is not being taking in consideration here.')

print()
b1 = input('')
print()
print('3. In case we choose numbers that do not generate a precise division,')
print('the quocient produce some number left and we want to know how much left,')
print('in that case we will use %, and the result should be', (x%y),'.')
print()
b1 = input('')
print()
print('CONCLUSION: A normal division of', x,'by', y,'is precisely', (x/y),',')
print('but a division of', x,' by', y,'not considering any eventual fration is', (x//y))
print('(if we had fraticionl, it was', (x%y))
print()
print('MALBA TAHAN!')
